[+] Add a initial content pack settings
Graylog2/graylog-ansible-role pull request #185
Opened 2022-01-05 12:43 UTC by sahya

Hi, there. 

I noticed a lack of configuration in templates/graylog.server.conf.j2. So I propose this configuration when I referenced  [[git.codificar.com.br/diogo.coutinho] this config](https://git.codificar.com.br/diogo.coutinho/laradock-multi-projetos/blob/master/graylog/config/graylog.conf).

Detail; The add settings are not contained the template of graylog.server.conf.j2 whether contained the default config parameter [defaults/main.yml#L120-L123](https://github.com/Graylog2/graylog-ansible-role/blob/648669639d995478d916e60c609d49bc5d983b58/defaults/main.yml#L120-L123).

## Notes for Reviewers

- [ ] The commit history must be preserved - please use the rebase-merge or standard merge option instead of squash-merge
- [ ] Sync up with the author before merging

2022-01-05 12:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Graylog2/graylog-ansible-role?pullRequest=185) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Graylog2/graylog-ansible-role?pullRequest=185) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Graylog2/graylog-ansible-role?pullRequest=185) it.</sub>

2022-01-26 18:20 UTC, sahya commented
@malcyon @mariussturm Hi, I'm sorry to mention you. Could you treat this pull request?

2022-01-26 20:22 UTC, malcyon commented
Hi @sahya,

My apologies for the delay. This change looks good to me. 

Could you sign the Contributor License Agreement? I see the `license/cla` check isn't completed yet.

2022-01-26 20:43 UTC, malcyon requested changes
Changes look good. Please sign the CLA and I will approve.

2022-01-27 17:32 UTC, sahya commented
@malcyon, I appreciate for reviewing this PR.
> Please sign the CLA and I will approve.
I just signed CLA for the first time. I was a little bit of a worried mind.

Excuse me, I have a question about lower compatibility. I think my written code doesn't consider the lower compatibility. So if it needs to consider under the 3.0 version for lower compatibility, Let me know it. And if you have some idea, could you tell me it?

2022-01-27 17:53 UTC, malcyon commented
> Excuse me, I have a question about lower compatibility. I think my written code doesn't consider the lower compatibility. So if it needs to consider under the 3.0 version for lower compatibility, Let me know it. And if you have some idea, could you tell me it?

I'll test it out and see. I think Graylog ignores any properties it doesn't understand.

2022-01-27 19:30 UTC, merged

2022-01-30 09:40 UTC, sahya commented
@malcyon 

> > Excuse me, I have a question about lower compatibility. I think my written code doesn't consider the lower compatibility. So if it needs to consider under the 3.0 version for lower compatibility, Let me know it. And if you have some idea, could you tell me it?
> 
> I'll test it out and see. I think Graylog ignores any properties it doesn't understand.

Okay, I understood it.

I appreciate you that are reviewing and testing the code.  Thank you.